web/hutia/core/views.py
from flask import render_template, Blueprint, request, redirect, url_for, make_response, flash, jsonify, send_file
from flask_login import current_user
from functools import wraps
from hutia.model import User, getPatients, getPatient, loadData, Evolution, loadAllEvolution, getEvaluation, getEvaluations, howManyData
import variables as v
import os
from werkzeug import secure_filename
from flask_cors import cross_origin
import time
import datetime
from sqlalchemy import and_
from subprocess import Popen, PIPE
import cv2
import base64

core = Blueprint('core', __name__)


def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if not current_user.is_authenticated:
            return redirect(url_for("user.login"))
        else:
            return f(*args, **kwargs)
    return wrap



@core.route("/index")
@login_required
def index():    
    
    if current_user.utype == 2:
        return redirect(url_for("core.patient_menu"))
    elif current_user.utype == 1:
        return redirect(url_for("core.manager_menu"))
    else:
        return redirect(url_for("user.logout"))


@core.route('/menu')
def patient_menu():
    return render_template("patient_index.html.j2", title="Menu", token=current_user.token, jitsi=v.JITSI)


@core.route('/menu-responsable')
def manager_menu():
    return render_template("manager_menu.html.j2", title="Menú Responsable", user=current_user)


@core.route('/patient/help')
def patient_ayuda():
    return render_template("patient_help.html.j2", title="Ayuda")

@core.route('/patient/evaluation')
def patient_evaluacion():
    if howManyData(current_user.idu) >= 2:
        da = True
        ev = getEvaluation(current_user.idu)
        res = (ev[0].data/ev[1].data-1)*100
    else:
        da = False
    res=0
    #if len(ev) != 2:
    #    return render_template("patient_index.html.j2", title="Menu", token=current_user.token)
    
    return render_template("patient_evaluation.html.j2", title="Evaluación", ev = res, da=da)

@core.route('/patient/tele')
def patient_telerehabilitation():
    return render_template("patient_telerehabilitation.html.j2", title="", token=current_user.token, jitsi=v.JITSI)


@core.route('/comunicacion', methods=["GET", "POST"])
def manager_com():
    if request.method=="POST":
        idu = request.form.get("patient",None)
        if idu != None:                
            patient = getPatient(idu)
            if patient != None:
                resp = make_response(render_template("manager_telerehabilitation.html.j2", title="Llamada con " + patient.name,token=patient.token, jitsi=v.JITSI))
                resp.headers["Access-Control-Allow-Origin"] = v.JITSI
                return resp
            elif idu == "grupal":
                resp = make_response(render_template("manager_telerehabilitation.html.j2", title="Llamada grupal ", token="reunion-grupal", jitsi=v.JITSI))
                resp.headers["Access-Control-Allow-Origin"] = v.JITSI
                return resp
            else:
                return "Usuario no encontrado",404
        else:
            return "Petición incorrecta",400
    patients = getPatients()
    return render_template("select_com.html.j2", title="Selección de Paciente", patients=patients)


@cross_origin
@core.route('/save-vid', methods=["POST"])
def save_vid():
    identifier = request.form.get("video_identifier")
    folder = os.path.join(v.basedir, "uploaded_videos", identifier)
    file = request.files["video-blob"]
    if file.filename != "":
        filename = secure_filename(file.filename)
        file.save(os.path.join(folder, filename))
        return "", 200
    else:
        return "", 400


@cross_origin
@core.route("/video-save-start", methods=["POST"])
def start_video_upload():
    identifier = request.form.get("video_identifier")
    os.makedirs(os.path.join(v.basedir, "uploaded_videos", identifier))
    return "", 200



@core.route("/upload_file", methods=["POST"])
def upload_file():
    folder = os.path.join(v.basedir, "uploaded_videos")
    file = request.files["zip"]
    if request.form['name'] != "":
        filename = secure_filename(request.form['name'])
        file.save(os.path.join(folder, filename))
        ts = filename.split("-")[0]
        machine = filename.split("-")[-1].split(".")[0]

        p = Popen(["bash", os.path.dirname(os.path.abspath(__file__))+"/merge.sh", folder, filename, ts+"-"+machine+".webm"], stdout=PIPE)

        return "", 200
    else:
        return "", 400


@core.route("/send_ip", methods=["POST"])
def send_ip():
    ip = request.form["ip"]
    user = request.form["user"]
    with open(os.path.join(v.basedir, "ips/ip.csv"), 'a') as csv:
        csv.write(user+","+ip+","+str(time.time())+"\n")
    return "", 200

@core.route("/statics", methods=["GET", "POST"])
def base_statics():
    if request.method == "GET":
        patients = getPatients()
        return render_template("manager_statics.html.j2", title="Selección de Paciente", patients=patients)
    else:
        return redirect(url_for("core.statics_menu", patient=request.form.get("patient",None)))

@core.route("/statics_menu/<patient>", methods=["GET"])
def statics_menu(patient):
    paciente = getPatient(patient)
    if paciente.utype != 2:
        return redirect(url_for("core.base_statics"))
    medidas = True
    if howManyData(patient) == 0:
        medidas = False
    return render_template("manager_statics_menu.html.j2", title="Menú de las medidas", name=paciente.name, idu=paciente.idu, medidas=medidas)

@core.route("/statics_menu/<patient>/add", methods=["GET", "POST"])
def statics_add(patient):
    paciente = getPatient(patient)
    if paciente.utype != 2:
        return redirect(url_for("core.base_statics"))
    if request.method == "GET":
        return render_template("statics/manager_add.html.j2", title="Añadir dato", name=paciente.name, date=datetime.datetime.now().strftime("%Y-%m-%d"), data=0)
    else:
        idu = paciente.idu
        date_origin = request.form.get("date",None)
        data = request.form.get("data",None)
        if date_origin is not None:
            date = int("".join(date_origin.split("-")))
            evolution = loadData(idu,date)
        if date is None or data is None:
            flash("No se ha rellenado correctamente", category="danger")
            return render_template("statics/manager_add.html.j2", title="Añadir dato", name=paciente.name, date=date_origin, data=data)
        elif evolution is not None:
            flash("Ya existe una medida para esa fecha en este paciente ", category="danger")
            return render_template("statics/manager_add.html.j2", title="Añadir dato", name=paciente.name, date=date_origin, data=data)
        else:      
            data = int(data)
            flash("Se ha añadido correctamente el valor"+str(evolution), category="success")
            evolution = Evolution(idu, date, data)
            v.db.session.add(evolution)
            v.db.session.commit()
            return redirect(url_for("core.statics_menu", patient=idu))

@core.route("/statics_menu/<patient>/mod", methods=["GET","UPDATE","DELETE"])
def statics_modify(patient):
    paciente = getPatient(patient)
    if paciente.utype != 2:
        return redirect(url_for("core.base_statics"))
    if request.method == "GET":
        return render_template("statics/manager_modify.html.j2",\
            title="Actualizar las medidas", name=paciente.name, idu=paciente.idu, evolution=loadAllEvolution(paciente.idu))
    elif request.method == "DELETE":
        date = request.form.get("date", None)
        if date is not None:
            Evolution.query.filter(and_(Evolution.date == date, Evolution.idu == paciente.idu)).delete()
            v.db.session.commit()
            return "", 200
        else:
            return "", 400
    elif request.method == "UPDATE":
        date = request.form.get("date", None)
        data = request.form.get("data", None)
        if date is not None and data is not None and data != "":
            loadData(paciente.idu, date).data = data
            v.db.session.commit()
            return "", 200
        else:
            return "", 400
    else:
        return "", 405

@core.route("/statics_menu/<patient>/show")
def show_statics(patient):
    paciente = getPatient(patient)
    if paciente.utype != 2:
        return redirect(url_for("core.base_statics"))
    eva = getEvaluations(paciente.idu)
    f = []
    e=[]
    for i in eva:
        f.append(v.app.jinja_env.filters["date"](i.date))
        e.append(i.data)
    return render_template("manager_statics_show.html.j2", title="Medidas de " + paciente.name, name=paciente.name, fecha = f, eva = e, idu=paciente.idu )

@core.route("/givemethepower")
@cross_origin(origin='*',headers=['Content- Type','Authorization'])
def give_me_the_code():

    r = {"code":"$('.action-btn').first().click()"}
    return jsonify(r)


@core.route("/videos", methods=["GET", "POST"])
def videos():

    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))

    ruta = os.path.join(v.basedir,"static","videos","processed")
    ficheros = os.listdir(ruta)
    ficheros.sort()
    if request.method == "GET":
        ficheros = list(set(map(lambda x: int(x.split("-")[1].split(".")[0]), filter(lambda x: x[0]!=".", ficheros))))
        ficheros.sort()
        return render_template("list_videos.html.j2", ficheros=ficheros, title="Lista de videos")
    else:
        f = request.form["file"]
        ficheros = list(filter(lambda x: x[-6:-1]+x[-1] == str(f)+".webm", ficheros))
        names = list(map(lambda x: datetime.datetime.fromtimestamp(int(x.split("-")[0])).strftime("%d de %m del %Y"),ficheros))
        # Si existe FIS 10 no funcionaría, que piense el siguiente
        imagenes = []
        for f in ficheros:
            vidcap = cv2.VideoCapture(os.path.join(ruta,f))
            success,image = vidcap.read()

web/hutia/user/views.py
from flask import render_template, Blueprint, redirect, url_for, request, flash, make_response
from hutia.user.forms import LoginForm, ChangePassForm
from flask_login import login_user, current_user, login_required
import variables as v
from hutia.model import User
import datetime


user = Blueprint("user", __name__)


@user.route("/", methods=["GET", "POST"])
def login():
    print(current_user)
    if current_user.is_authenticated:
        return redirect(url_for('core.index'))
    form = LoginForm()
    if request.method == "POST":
        if form.validate_on_submit():
            user = User.query.filter_by(identity_name=form.identity.data).first()
            if user is not None and user.check_password(form.password.data):
                #login_user(user)
                response = make_response(redirect(url_for('core.index')))
                expire_date = datetime.datetime.now()
                expire_date = expire_date + datetime.timedelta(days=365000)
                response.set_cookie("token", user.token, expires=expire_date)
                return response
            else:
                flash("Error de credenciales", "danger")

    return render_template("login.html.j2", title="Hutia", form=form)


@v.login_manager.request_loader
def load_user_from_request(request):
    token = request.cookies.get('token')
    user = User.query.filter_by(token=token).first()
    return user

@user.route("/change_password", methods=["GET", "POST"])
def change_pass():
    print(current_user)
    form = ChangePassForm()
    if request.method == "POST":
        if form.validate_on_submit():
            user = current_user
            if user is not None and user.check_password(form.password_old.data):
                #login_user(user)
                response = make_response(redirect(url_for('core.index')))
                user.set_password(form.password_new.data)
                return response
            else:
                flash("Error de credenciales", "danger")
        else:
            flash("Las contraseñas no coinciden", "warning")
    return render_template("change_pass.html.j2", title="Hutia", form=form)

@user.route("/logout", methods=["GET"])
def logout():
    response = make_response(redirect(url_for('core.index')))
    response.set_cookie("token", "", expires=0)
    return response

web/hutia/templates/aux_menu_resp.html.j2
<div class="btn-group" id="config" role="group">
  <div class="btn-group" role="group">
    <button id="btnGroupDrop3" type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-tools"></i></button>
    <div class="dropdown-menu" aria-labelledby="btnGroupDrop3">
      <a class="dropdown-item" href="{{ url_for("user.change_pass") }}">Cambiar contraseña</a>
      <a class="dropdown-item" href="{{ url_for("user.logout") }}">Cerrar sessión</a>
    </div>
  </div>
</div>

web/hutia/templates/base.html.j2
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{{ url_for('static', filename="css/normalizer.css") }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename="css/bootstrap-reboot.css") }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename="css/bootstrap.css") }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename="css/bootstrap-grid.css") }}" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@jlgarridol/modalizer.js@1.0.2/dist/css/modalizer.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename="css/custom.css") }}" />
        {% block css %}
        {% endblock %}

        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <title>{{ title }}</title>
    </head>
    <body class="{% block body_class %}{% endblock %}" style="padding-right:0">
        <div id="MOD_supreme-container" class="MOD_supreme-container">
        {% block before_anyelse %}
        {% endblock %}

        {% block content %}
        {% endblock %}

        {% block volver %}
        <div id="volver" class="container-fluid">
            <div class="row">
                <div class="col-md-4 offset-md-2 mb-4">
                    <div class="d-flex align-items-center">
                        <a type="button" class="btn btn-info btn-sm ml-auto" href="{{url_for("core.manager_menu")}}">Volver al inicio</a>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="d-flex align-items-center">
                        <a type="button" class="btn btn-info btn-sm mr-auto" href="#a" onclick="window.history.back()">Volver atrás</a>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}

        {% block after_anyelse %}
        
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <p class="text-center"> Proyecto FIS: Estudio de factibilidad y
                                            coste-efectividad del uso de telemedicina
                                            con un equipo multidisciplinar para
                                            prevención de caídas en la enfermedad de
                                            Parkinson (2020-2023) PI19/00670
                    </p>
                </div>
            </div>
        </div>
        </div>
        {%block modals %}{%endblock%}
        {% endblock %}
        <script src="https://kit.fontawesome.com/3292dc6a03.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@jlgarridol/modalizer.js@1.0.2/dist/js/modalizer.min.js"></script>
        {% block js %}
        {% endblock %}
        
        
    </body>
</html>

web/hutia/templates/change_pass.html.j2
{% extends "base.html.j2" %}

{% block content %}

<div class="jumbotron">
    <div class="container">
        <div class="row">
            <fieldset class="col-6 offset-3">
                <form class="form-horizontal" method="POST">
                    <h3 class="text-center">Cambiar la contraseña</h3>
                    {{ form.hidden_tag()}}
                    {% for category, message in get_flashed_messages(with_categories=True) %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">{{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                    <div class="control-group">
                        {{form.password_old.label(class="control")}}
                        {{form.password_old(class="form-control")}}<br>
                    </div>
                    <div class="control-group">
                        {{form.password_new.label(class="form-group")}}
                        {{form.password_new(class="form-control")}}<br>
                    </div>
                    <div class="control-group">
                        {{form.password_new_re.label(class="form-group")}}
                        {{form.password_new_re(class="form-control")}}<br>
                    </div>
                    <div class="control-group">
                        {{form.submit(class="btn btn-primary")}}
                    </div>
                </form>
            </fieldset>
        </div>
    </div>
</div>

{% endblock %}

web/hutia/templates/list_videos.html.j2
{% extends "base.html.j2" %}

{% block content %}
<div class="jumbotron">
    <fieldset>
        <form class="form-horizontal" method="POST">
            <div class="row">
                <h3 class="col-md-12 text-center">Seleccione la máquina de la que quiera ver los vídeos</h3>
            </div>
            <div class="row">
                <div class="control-group mt-3 offset-md-5 col-md-2">
                    <select class="custom-select" name="file">
                        {% for f in ficheros %}
                            <option value="{{f}}">FIS HUBU {{f}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>    
            <div class="row">
                <div class="control-group mt-3 offset-md-5 col-md-2 d-flex">
                    <button type="submit" class="btn btn-primary m-auto">Ver vídeos</button>
                </div>
            </div>
        </form>
    </fieldset>
</div>

{% endblock %}

web/hutia/templates/login.html.j2
{% extends "base.html.j2" %}

{% block content %}

<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-2">
                <img src="{{ url_for('static', filename='img/sacyl.png') }}" style="height: 4rem;">
            </div>
            <div class="col-1">
                <img src="{{ url_for('static', filename='img/fundacion.png') }}" style="height: 4rem;">
            </div>
            <div class="col-6">
            </div>
            <div class="col-2">
                <img src="{{ url_for('static', filename='img/Escudo Color TC.png') }}" style="height: 4rem;">
            </div>
            <div class="col-1">
                <img src="{{ url_for('static', filename='img/admirable.png') }}" style="height: 4rem;">
            </div>
        </div>
        {% for category, message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ category }} alert-dismissible fade show mt-5 mb-2" role="alert">{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        <div class="row">
            <fieldset class="col-6 offset-3">
                <form class="form-horizontal" method="POST">
                    <h3 class="text-center">Iniciar sesión</h3>
                    {{ form.hidden_tag()}}
                    <div class="control-group">
                        {{form.identity.label(class="control")}}
                        {{form.identity(class="form-control")}}<br>
                    </div>
                    <div class="control-group">
                        {{form.password.label(class="form-group")}}
                        {{form.password(class="form-control")}}<br>
                    </div>
                    <div class="control-group">
                        {{form.submit(class="btn btn-primary")}}
                    </div>
                </form>
            </fieldset>
        </div>
    </div>
</div>

{% endblock %}

{% block volver %}{% endblock %}

web/hutia/templates/machine_videos.html.j2
{% extends "base.html.j2" %}

{% block content %}
<div class="jumbotron">
    <fieldset>
        <form class="form-horizontal" method="POST">
            <div class="row">
                <h3 class="col-md-12 text-center">Seleccione el vídeo</h3>
            </div>
            <div class="row">
                {% for f in ficheros %}
                <div class="control-group mt-3 col-md-4 modalinit videolauncher" data-modal="modal" style="cursor: pointer;" data-file="{{f}}" data-name="{{names[loop.index0]}}">
                    <img src="data:image/png;base64, {{ imagenes[loop.index0] | safe }}" class="img-fluid 
                    p-2"/>
                    <h5 class="text-center">{{ names[loop.index0] }}</h5>
                </div>
                {% endfor %}
            </div>    
        </form>
    </fieldset>
</div>
{% endblock %}

{% block js %}
<script>
    $("document").ready(function(){
        $(".videolauncher").each(function(){
            $(this).click(function(){
                let it = $(this);
                let file = it.data("file");
                let name = it.data("name");
                $("#title").text(name);
                $("#descargarbtn").attr("href","/descargar/"+file);
                $("#video").html("<source src=\""+"/static/videos/processed/"+file+"\" type='video/webm'>")
                //$("#videosrc").attr("src","/static/videos/processed/"+file)
            });
        });
    });
</script>
{% endblock %}

{% block modals %}
    <div class="modal modalizer animate__animated animate__faster" id="modal" tabindex= "-1" role="dialog" data-animate-in="zoomIn" data-animate-out="zoomOut">
        <div class="modal-dialog fullscreen modal-dialog-centered" role="document">
        <div class="modal-content fullscreen">
        <div class="modal-header fullscreen">
            <h5 class="modal-title" id="title"></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body d-flex justify-content-center align-items-center" style="width: auto">
            <video width="1280" height="720" controls muted seek id="video">
            </video>
        </div>
        <div class="modal-footer fullscreen">
            <a type="button" class="btn btn-primary btn-lg" href="#" id="descargarbtn" target="_blank">Descargar</a>
            <button type="button" class="btn btn-secondary closemodal">Cerrar</button>
        </div>
        </div>
    </div>
    </div>
{%endblock%}

web/hutia/templates/manager_menu.html.j2
{% extends "base.html.j2" %}

{% block content %}
<div class="jumbotron position-relative">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-center">Menú</h3>
            <h4 class="text-center">Hola {{user.name}}</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 offset-md-3 mt-5">
            <div class="d-flex align-items-center">
                <a type="button" class="btn btn-primary btn-lg m-auto" href="{{url_for("core.manager_com")}}">Comunicación</a>
            </div>
        </div>
        <div class="col-md-2 mt-5">
            <div class="d-flex align-items-center">
                <a type="button" class="btn btn-success btn-lg m-auto" href="{{url_for("core.videos")}}">Ver sesiones anteriores</a>
            </div>
        </div>
        <div class="col-md-2 mt-5">
            <div class="d-flex align-items-center">
                <a type="button" class="btn btn-info btn-lg m-auto" href="{{url_for("core.base_statics")}}">Evolución de pacientes</a>
            </div>
        </div>
    </div>
    {% include "aux_menu_resp.html.j2" %}
</div>

{% endblock %}

{% block volver %}{% endblock %}

web/hutia/templates/manager_statics.html.j2
{% extends "base.html.j2" %}

{% block content %}
<div class="jumbotron">
    <fieldset>
        <form class="form-horizontal" method="POST">
            <div class="row">
                <h3 class="col-md-12 text-center">Seleccione al paciente cuya evolución quieras revisar</h3>
            </div>
            <div class="row">
                <div class="control-group mt-3 offset-md-5 col-md-2">
                    <select class="custom-select" name="patient">
                        {% for u in patients %}
                            <option value="{{u.idu}}">{{u.name}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>    
            <div class="row">
                <div class="control-group mt-3 offset-md-5 col-md-2 d-flex">
                    <button type="submit" class="btn btn-primary m-auto">Menú de evolución</button>
                </div>
            </div>
        </form>
    </fieldset>
</div>

{% endblock %}

web/hutia/templates/manager_statics_show.html.j2
{% extends "base.html.j2" %}

{% block content %}
    <div class="jumbotron container-fluid">
        <div class="row" id="out">
            <div class="col-12 d-flex justify-content-center">
                <h1>Medidas para {{name}}</h1>
            </div>
            <div class="col-md-6 offset-md-3 d-flex justify-content-center">
               <canvas id="myChart"></canvas> 
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels:{{fecha}},
        datasets:[{
            label:"Medida",
            borderColor:"red",
            backgroundColor:"red",
            fill:false,
            data:{{eva}},
            borderWidth:1,
            yAxisId:"y"
        }]
    },
    options: {
        responsive:true,
        title:{
            display:true
        },
        scales:{
            yAxes:[{
                id:"y",
                position:"left",
                type:"linear",
                display:true
            }]
        }
    }
});

console.log({{f}});

</script>
{% endblock %}

web/hutia/templates/patient_evaluation.html.j2
{% extends "patient_menu.html.j2" %}

{% block btn_azul %}{% endblock %}
{% block btn_verde %}{% endblock %}
{% block btn_rojo %}{% endblock %}

{% block before_menu %}
    {% if da %}
        <div class="row" id="out">
            <div class="col-12 d-flex justify-content-center">
                <h1 class="text-center display-1">
                {% if ev < 0 %}
                    Ánimo podemos mejorar.
                {% elif ev < 5 %}
                    Vas por buen camino.
                {% elif ev <10 %}
                    Bien hecho.
                {% else %}
                    Muy bien.
                {% endif %}
                <!--has obtenido un {{"{:.2f}".format(ev)}}% con respecto al dato anterior.-->
                </h1>
            </div>
            <div class="col-12 d-flex justify-content-center">
                {% if ev < 0 %}
                    <img src="{{ url_for('static', filename='img/mal.png') }}" class="img-fluid" style="width: 30%;"/>
                {% elif ev < 5 %}
                    <img src="{{ url_for('static', filename='img/mejorar.png') }}" class="img-fluid" style="width: 30%;"/>
                {% elif ev <10 %}
                    <img src="{{ url_for('static', filename='img/bien.png') }}" class="img-fluid" style="width: 30%;"/>
                {% else %}
                    <img src="{{ url_for('static', filename='img/muybien.png') }}" class="img-fluid" style="width: 30%;"/>
                {% endif %}
            </div>
        </div>
    {% else %}
        <div class="row" id="out">
            <div class="col-12 d-flex justify-content-center">
                <h1 class="text-center display-1">Bien hecho.</h1>
            </div>
            <div class="col-12 d-flex justify-content-center">
                <img src="{{ url_for('static', filename='img/bien.png') }}" class="img-fluid" style="width: 30%;"/>
            </div>
        </div>
    {% endif %}
{% endblock %}

web/hutia/templates/patient_index.html.j2
{% extends "patient_menu.html.j2" %}

{% block btn_amarillo %}
<button class="btn btn-select btn-lg p-2 px-5 mt-5 text-uppercase rounded-circle text-center font-weight-bolder display-4" onclick="btn_b_function()" id="btn_amarillo">Apagar</button>
{% endblock %}

{% block menujs %}
<script>
    $("document").ready(function(){
        btn_azul.text("Llamar al médico");
        btn_verde.text("Reunión grupal");
        btn_rojo.text("Evolución")
    });
</script>

{% endblock %}

{% block azul_function %}
window.location.href = "{{jitsi}}/{{token}}";
{% endblock %}

 {% block verde_function %}
window.location.href = "{{jitsi}}reunion-grupal";
 {% endblock %}

 {% block rojo_function %}
 window.location.href = "{{ url_for("core.patient_evaluacion")}}";
 {% endblock %}