web/hutia/core/views.py
from flask import render_template, Blueprint, request, redirect, url_for, make_response, flash, jsonify, send_file
from flask_login import current_user
from functools import wraps
from hutia.model import User, getPatients, getPatient, loadData, Evolution, loadAllEvolution, getEvaluation, getEvaluations, howManyData
import variables as v
import os
from werkzeug import secure_filename
from flask_cors import cross_origin
import time
import datetime
from sqlalchemy import and_
from subprocess import Popen, PIPE
import cv2
import base64

core = Blueprint('core', __name__)


def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if not current_user.is_authenticated:
            return redirect(url_for("user.login"))
        else:
            return f(*args, **kwargs)
    return wrap



@core.route("/index")
@login_required
def index():    
    
    if current_user.utype == 2:
        return redirect(url_for("core.patient_menu"))
    elif current_user.utype == 1:
        return redirect(url_for("core.manager_menu"))
    else:
        return redirect(url_for("user.logout"))


@core.route('/menu')
def patient_menu():
    return render_template("patient_index.html.j2", title="Menu", token=current_user.token, jitsi=v.JITSI)


@core.route('/menu-responsable')
def manager_menu():
    return render_template("manager_menu.html.j2", title="Menú Responsable", user=current_user)


@core.route('/patient/help')
def patient_ayuda():
    return render_template("patient_help.html.j2", title="Ayuda")

@core.route('/patient/evaluation')
def patient_evaluacion():
    if howManyData(current_user.idu) >= 2:
        da = True
        ev = getEvaluation(current_user.idu)
        res = (ev[0].data/ev[1].data-1)*100
    else:
        da = False
    res=0
    #if len(ev) != 2:
    #    return render_template("patient_index.html.j2", title="Menu", token=current_user.token)
    
    return render_template("patient_evaluation.html.j2", title="Evaluación", ev = res, da=da)

@core.route('/patient/tele')
def patient_telerehabilitation():
    return render_template("patient_telerehabilitation.html.j2", title="", token=current_user.token, jitsi=v.JITSI)


@core.route('/comunicacion', methods=["GET", "POST"])
def manager_com():
    if request.method=="POST":
        idu = request.form.get("patient",None)
        if idu != None:                
            patient = getPatient(idu)
            if patient != None:
                resp = make_response(render_template("manager_telerehabilitation.html.j2", title="Llamada con " + patient.name,token=patient.token, jitsi=v.JITSI))
                resp.headers["Access-Control-Allow-Origin"] = v.JITSI
                return resp
            elif idu == "grupal":
                resp = make_response(render_template("manager_telerehabilitation.html.j2", title="Llamada grupal ", token="reunion-grupal", jitsi=v.JITSI))
                resp.headers["Access-Control-Allow-Origin"] = v.JITSI
                return resp
            else:
                return "Usuario no encontrado",404
        else:
            return "Petición incorrecta",400
    patients = getPatients()
    return render_template("select_com.html.j2", title="Selección de Paciente", patients=patients)


@cross_origin
@core.route('/save-vid', methods=["POST"])
def save_vid():
    identifier = request.form.get("video_identifier")
    folder = os.path.join(v.basedir, "uploaded_videos", identifier)
    file = request.files["video-blob"]
    if file.filename != "":
        filename = secure_filename(file.filename)
        file.save(os.path.join(folder, filename))
        return "", 200
    else:
        return "", 400


@cross_origin
@core.route("/video-save-start", methods=["POST"])
def start_video_upload():
    identifier = request.form.get("video_identifier")
    os.makedirs(os.path.join(v.basedir, "uploaded_videos", identifier))
    return "", 200



@core.route("/upload_file", methods=["POST"])
def upload_file():
    folder = os.path.join(v.basedir, "uploaded_videos")
    file = request.files["zip"]
    if request.form['name'] != "":
        filename = secure_filename(request.form['name'])
        file.save(os.path.join(folder, filename))
        ts = filename.split("-")[0]
        machine = filename.split("-")[-1].split(".")[0]

        p = Popen(["bash", os.path.dirname(os.path.abspath(__file__))+"/merge.sh", folder, filename, ts+"-"+machine+".webm"], stdout=PIPE)

        return "", 200
    else:
        return "", 400


@core.route("/send_ip", methods=["POST"])
def send_ip():
    ip = request.form["ip"]
    user = request.form["user"]
    with open(os.path.join(v.basedir, "ips/ip.csv"), 'a') as csv:
        csv.write(user+","+ip+","+str(time.time())+"\n")
    return "", 200

@core.route("/statics", methods=["GET", "POST"])
def base_statics():
    if request.method == "GET":
        patients = getPatients()
        return render_template("manager_statics.html.j2", title="Selección de Paciente", patients=patients)
    else:
        return redirect(url_for("core.statics_menu", patient=request.form.get("patient",None)))

@core.route("/statics_menu/<patient>", methods=["GET"])
def statics_menu(patient):
    paciente = getPatient(patient)
    if paciente.utype != 2:
        return redirect(url_for("core.base_statics"))
    medidas = True
    if howManyData(patient) == 0:
        medidas = False
    return render_template("manager_statics_menu.html.j2", title="Menú de las medidas", name=paciente.name, idu=paciente.idu, medidas=medidas)

@core.route("/statics_menu/<patient>/add", methods=["GET", "POST"])
def statics_add(patient):
    paciente = getPatient(patient)
    if paciente.utype != 2:
        return redirect(url_for("core.base_statics"))
    if request.method == "GET":
        return render_template("statics/manager_add.html.j2", title="Añadir dato", name=paciente.name, date=datetime.datetime.now().strftime("%Y-%m-%d"), data=0)
    else:
        idu = paciente.idu
        date_origin = request.form.get("date",None)
        data = request.form.get("data",None)
        if date_origin is not None:
            date = int("".join(date_origin.split("-")))
            evolution = loadData(idu,date)
        if date is None or data is None:
            flash("No se ha rellenado correctamente", category="danger")
            return render_template("statics/manager_add.html.j2", title="Añadir dato", name=paciente.name, date=date_origin, data=data)
        elif evolution is not None:
            flash("Ya existe una medida para esa fecha en este paciente ", category="danger")
            return render_template("statics/manager_add.html.j2", title="Añadir dato", name=paciente.name, date=date_origin, data=data)
        else:      
            data = int(data)
            flash("Se ha añadido correctamente el valor"+str(evolution), category="success")
            evolution = Evolution(idu, date, data)
            v.db.session.add(evolution)
            v.db.session.commit()
            return redirect(url_for("core.statics_menu", patient=idu))

@core.route("/statics_menu/<patient>/mod", methods=["GET","UPDATE","DELETE"])
def statics_modify(patient):
    paciente = getPatient(patient)
    if paciente.utype != 2:
        return redirect(url_for("core.base_statics"))
    if request.method == "GET":
        return render_template("statics/manager_modify.html.j2",\
            title="Actualizar las medidas", name=paciente.name, idu=paciente.idu, evolution=loadAllEvolution(paciente.idu))
    elif request.method == "DELETE":
        date = request.form.get("date", None)
        if date is not None:
            Evolution.query.filter(and_(Evolution.date == date, Evolution.idu == paciente.idu)).delete()
            v.db.session.commit()
            return "", 200
        else:
            return "", 400
    elif request.method == "UPDATE":
        date = request.form.get("date", None)
        data = request.form.get("data", None)
        if date is not None and data is not None and data != "":
            loadData(paciente.idu, date).data = data
            v.db.session.commit()
            return "", 200
        else:
            return "", 400
    else:
        return "", 405

@core.route("/statics_menu/<patient>/show")
def show_statics(patient):
    paciente = getPatient(patient)
    if paciente.utype != 2:
        return redirect(url_for("core.base_statics"))
    eva = getEvaluations(paciente.idu)
    f = []
    e=[]
    for i in eva:
        f.append(v.app.jinja_env.filters["date"](i.date))
        e.append(i.data)
    return render_template("manager_statics_show.html.j2", title="Medidas de " + paciente.name, name=paciente.name, fecha = f, eva = e, idu=paciente.idu )

@core.route("/givemethepower")
@cross_origin(origin='*',headers=['Content- Type','Authorization'])
def give_me_the_code():

    r = {"code":"$('.action-btn').first().click()"}
    return jsonify(r)


@core.route("/videos", methods=["GET", "POST"])
def videos():

    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))

    ruta = os.path.join(v.basedir,"static","videos","processed")
    ficheros = os.listdir(ruta)
    ficheros.sort()
    if request.method == "GET":
        ficheros = list(set(map(lambda x: int(x.split("-")[1].split(".")[0]), filter(lambda x: x[0]!=".", ficheros))))
        ficheros.sort()
        return render_template("list_videos.html.j2", ficheros=ficheros, title="Lista de videos")
    else:
        f = request.form["file"]
        ficheros = list(filter(lambda x: x[-6:-1]+x[-1] == str(f)+".webm", ficheros))
        names = list(map(lambda x: datetime.datetime.fromtimestamp(int(x.split("-")[0])).strftime("%d de %m del %Y"),ficheros))
        # Si existe FIS 10 no funcionaría, que piense el siguiente
        imagenes = []
        for f in ficheros:
            vidcap = cv2.VideoCapture(os.path.join(ruta,f))
            success,image = vidcap.read()

web/hutia/templates/statics/manager_add.html.j2
{% extends "base.html.j2" %}

{% block content %}
<div class="jumbotron">
    <fieldset>
        <form class="form-horizontal" method="POST">
            <div class="row">
                <h3 class="col-md-12 text-center">Añadir medida a {{name}}</h3>
            </div>
            {% for category, message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">{{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
            <div class="row">
                <div class="control-group mt-3 col-md-2 offset-md-4 text-center">
                    <label><strong>Fecha</strong></label> <input class="form-control" type="date" name="date" value="{{date}}" required="required">
                </div>
                <div class="control-group mt-3 col-md-2 text-center">
                    <label><strong>Medida</strong></label> <input class="form-control" type="number" name="data" value="{{data}}" required="required">
                </div>
            </div>    
            <div class="row">
                <div class="control-group mt-3 offset-md-5 col-md-2">
                    <button type="submit" class="btn btn-primary btn-block">Añadir</button>
                </div>
            </div>
        </form>
    </fieldset>
</div>

{% endblock %}

web/hutia/templates/statics/manager_modify.html.j2
{% extends "base.html.j2" %}

{% block content %}
<div class="jumbotron">
    <div class="row">
        <h3 class="col-md-12 text-center">Actualizar medidas de {{name}}</h3>
    </div>
    {% for category, message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">{{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    <div class="col-md-6 offset-md-3 mt-5 text-center">
        <table class="table table-striped table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Fecha</th>
                    <th scope="col">Medida</th>
                    <th scope="col">Actualizar</th>
                    <th scope="col">Borrar</th>
                </tr>
            </thead>
            <tbody>
                {% for dato in evolution %}
                    <tr>
                        <th scope="row">{{dato.date | date}}</th>
                        <td><input value="{{dato.data}}" type="number" class="form-control" id="{{dato.date}}"></td>
                        <td><button class="btn btn-block btn-warning" data-toggle="modal" data-target="#updateModal" data-to="{{dato.date}}">Actualizar</button></td>
                        <td><button class="btn btn-block btn-danger" data-toggle="modal" data-target="#deleteModal" data-to="{{dato.date}}">Borrar</button></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{# Modal de actualización #}
<div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="Update" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateTitle">¿Estás seguro que quieres actualizar la medida?<span class="badge badge-warning">Esta acción no se puede deshacer<span></h5>
        
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-warning" id="confirmUpdate">Confirmar actualización</button>
      </div>
    </div>
  </div>
</div>

{# Modal de borrado #}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="Delete" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteTitle">¿Estás seguro que quieres borrar la medida?<span class="badge badge-danger">Esta acción no se puede deshacer<span></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-danger" id="confirmDelete">Confirmar borrado</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block js %}
<script>
    $('#updateModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget);
        var to = button.data('to')
        var modal = $(this)
        modal.find('#confirmUpdate').click(function(){
                console.log("Confirmar actualización para el dato de la fecha "+to);
                $.ajax({
                    url: "{{ url_for("core.statics_modify", patient=idu) }}",
                    type: "UPDATE",
                    contentType: 'application/x-www-form-urlencoded',
                    data: "date="+to+"&data="+$("#"+to).val(),
                    success: function(result){
                        location.reload(true);
                    },
                    error: function(result){
                        location.reload(true);
                    }
                });
                modal.modal("hide");
            })
    });

    $("#updateModal").on('hidden.bs.modal', function(e){
        $(this).find("#confirmUpdate").off();
    });
</script>

<script>
    $('#deleteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget); 
        var to = button.data('to'); 
        var modal = $(this);
        modal.find('#confirmDelete').click(function(){
                console.log("Confirmar borrado para el dato de la fecha "+to);
                $.ajax({
                    url: "{{ url_for("core.statics_modify", patient=idu) }}",
                    type: "DELETE",
                    contentType: 'application/x-www-form-urlencoded',
                    data: "date="+to,
                    success: function(result){
                        location.reload(true);
                    },
                    error: function(result){
                        location.reload(true);
                    }
                });
                modal.modal("hide");
            });
        
    });

    $("#deleteModal").on('hidden.bs.modal', function(e){
        $(this).find("#confirmDelete").off();
    });
</script>
{% endblock %}